#!/usr/bin/env bash
# script by cyndrdev

# wrapper around ufetch for prettier screenshots

x=$RANDOM
y=$RANDOM

let "x %= 1580"
let "y %= 920"

let "x += 20"
let "y += 90"

bspc rule -a URxvt:fetch state=floating rectangle="280x160+$x+$y"

read -r -d '' cmd <<EOM
cd $HOME/.scripts;
clear;
tput civis;
./ufetch-core;
while [ 1 ];
do read -s;
done;
EOM

urxvt -name fetch -e bash -c "$cmd"
